#encoding:utf-8
webInfo = {
    'gexing.com':{
         'category':'动漫',
         'domain':'gexing.com',
         'sourceUrl':{
             'www.gexing.com/shaitu/t/萌物卡通/1':373,
             'www.gexing.com/shaitu/t/漫画/new/1':509,
             'www.gexing.com/shaitu/t/动漫图片/1':123,
         },
         'urlPattern':'http://www.gexing.com/shaitu/\d+.html',
         'fenyePattern':['/1', '/%d'],
         'bodyPattern':{"tag":"ul", "class":["ttTxtImg"]},
         'textPattern': {"tag":"div", "class":["left"]},
         'titleXpath': '//h2/text()',
         'imgPattern':ur'(?is)(<img.*?>)',
         'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
         'isAlbum':1
    },
    'sj33.cn':{
        'category':'动漫', 
        'domain':'sj33.cn', 
        'sourceUrl':{
            'http://www.sj33.cn/cg/chys/P1.html':194,
            'http://www.sj33.cn/cg/sdys/P1.html':9,
        },
        'bodyPattern':{"tag":"div", "class":["artcon"]},
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':ur'http.*\.(jpg|jpeg|gif|JPG|png)',
        'urlPattern':'http://www.sj33.cn/.*/\d+/\d+.html',
        'textXpath': '//h1/text()',
        'myposXpath': '//div[@id="loat6"]/a/text()',
        'fenyePattern':['P1','P%d'],
        'isAlbum':1
    },
    'niutuku.com': {
        'category': '动漫',
        'domain': 'niutuku.com',
        'sourceUrl': {
            'http://niutuku.com/shoujibizhi/3/index.shtml':195
	},
        'urlPattern': 'http://niutuku.com/(hd|shoujibizhi|bizhi)/\d+.shtml',
        'bodyPattern': {'tag': 'dl','class': ['container', 'preview']},'imgPattern': u'(?is)(<img.*?>)',
        'myposPattern': {'tag': 'div','class': ['place']},'fenyePattern': [
		      '.shtml', '_%d.shtml'],
        'imgUrlPattern': u'http.*\.(jpg|jpeg|gif|JPG|png)',
        'imgReplace': [['190', '960']],
        'isAlbum': 1
    },

    'taopic.com':{
        'category':'动漫',
        'domain':'taopic.com',
        'sourceUrl':{
            'http://www.taopic.com/tuku/illustration/list_1.html':59,
            'http://www.taopic.com/tuku/katongfengjing/list_1.html':4,
            'http://www.taopic.com/tuku/katongdongwu/list_1.html':33,
            'http://www.taopic.com/tuku/qitakatong/list_1.html':19,
        },
        'urlPattern':'http://www.taopic.com/tuku/\d+/\d+.html',
        'fenyePattern':['1.html', '%d.html'],
        'bodyPattern':{"tag":"div", "class":["viewBoxPad"]},
        'myposPattern': {"tag":"div", "class":["crumbs"]},
        'textPattern': {"tag":"div", "class":["viewBoxPad"]},
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
        'isAlbum':1
    },

    'pchome.net': {
        'category': '动漫',
        'domain': 'pchome.net',
	'sourceUrl': {
            'http://download.pchome.net/wallpaper/dongman/p1/':13,
            'http://download.pchome.net/wallpaper/notebook/dongman/t24p1/':5,
            'http://download.pchome.net/wallpaper/pad/dongman/p1/':5,
            'http://download.pchome.net/wallpaper/mobile/dongman/p1/':21,
        },
        'urlPattern': 'http://download.pchome.net/wallpaper/info-.*.html',
        'imgUrlPattern': u'http.*\.(jpg|jpeg|gif|JPG|png)',
        'fenyePattern': ['p1/', 'p%d/'],
        'detailFenyePattern': ['-1-', '-%d-'],
        'titleXpath': '//h3/a/text()',
        'imgXpath': '//img[@id="bigImg"]/@src',
        'contentXpath': '',
        'timeXpath': '',
        'myposXpath': '//div[@class="location-nav"]/div/a/text()',
        'detailFyXpath': '//h3/span/text()',
        'isAlbum': 2
    },

    '51tietu.net':{
         'category':'动漫',
         'domain':'51tietu.net',
         'sourceUrl':{
             'http://www.51tietu.net/2ciyuan/':50,
             'http://www.51tietu.net/kttp/':91,
         },
         'fenyePattern':['', '%d'],
         'urlPattern':'http://www.51tietu.net/.*/\d+.html',
         'bodyPattern':{"tag":"div", "class":["pic-box"]},
         'myposPattern': {"tag":"div", "class":["title"]},
         'textPattern': {"tag":"div", "class":["pic-box"]},
         'imgPattern':ur'(?is)(<img.*?>)',
         'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
         'isAlbum':1
    },

    'tooopen.com':{
         'category':'动漫',
         'domain':'tooopen.com',
         'sourceUrl':{
             'http://www.tooopen.com/work/15_0_1_1.aspx':86,
             'http://www.tooopen.com/work/15_52_1_1.aspx':38,
             'http://www.tooopen.com/work/15_53_1_1.aspx':43,
             'http://www.tooopen.com/img/98_680_1_1.aspx':101,
             'http://www.tooopen.com/aicdr/117_310_1_1.aspx':180,
         },
         'fenyePattern':['1.aspx', '%d.aspx'],
         'urlPattern':'www.tooopen.com/.*view/\d+.html',
         'bodyPattern':{"tag":"div", "class":["pic-box"]},
         'myposPattern': {"tag":"div", "class":["loca"]},
         'textPattern': {"tag":"li", "class":["key"]},
         'imgPattern':ur'(?is)(<img.*?>)',
         'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
         'isAlbum':1
    },

    '4j4j.cn':{
        'category':'动漫', 
        'domain':'4j4j.cn', 
        'sourceUrl':{
            'http://www.4j4j.cn/zmbz/f-cate61_1.html':13,
            'http://www.4j4j.cn/zmbz/f-cate42_1.html':12,
            'http://www.4j4j.cn/sjbz/f-cate70_1.html':16,
            'http://www.4j4j.cn/sjbz/f-cate69_1.html':21,
        },
        'urlPattern':'http://www.4j4j.cn/.*/\d+.html',
        'bodyPattern':{"tag":"ul", "id":["clearfix"]},
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':ur'http://pic.4j4j.cn/upload/star/\d+_\d+/\d+.(jpg|jpeg|gif|JPG|png)|http://pic.4j4j.cn/upload/pic/\d+/[A-Za-z0-9]+.(jpg|jpeg|gif|JPG|png)',
        'myposPattern': {"tag":"div", "class":["main_nav"]}, 
        'fenyePattern':['1.html','%d.html'],
        'isAlbum':1
    },
    'jj20.com':{
        'category':'动漫', 
        'domain':'jj20.com', 
        'sourceUrl':{
            'http://www.jj20.com/bz/ktmh/list_16_1.html':39,
            'http://www.jj20.com/bz/slkt/slkt/list_107_1.html':4,
        },
        'urlPattern':'http://www.jj20.com/bz/.*/\d+.html',
        'bodyPattern':{"tag":"div", "class":["photo"]},
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':ur'http.*\.(jpg|jpeg|gif|JPG|png)',
        'fenyePattern':['1.html','%d.html'],
        'detailFenyePattern':['.html','_%d.html'],
        'isAlbum':1
    },

     '55156.com':{
         'category':'动漫',
         'domain':'55156.com',
         'sourceUrl':{
                 'http://www.55156.com/katongdongman/list_62_1.html':293,
                 'http://www.55156.com/katongdongman/katongtupian/list_65_1.html':87,
                 'http://www.55156.com/katongdongman/cosplay/list_73_1.html':24,
                 'http://www.55156.com/katongdongman/hzw/list_127_1.html':17,
                 'http://www.55156.com/katongdongman/hyrz/list_128_1.html':12,
                 'http://www.55156.com/katongdongman/yxlm/list_129_1.html':25,
                 'http://www.55156.com/katongdongman/eth/list_132_1.html':16,
             },
         'urlPattern':'http://www.55156.com/katongdongman/.*?/\d+.html',
         'fenyePattern':['1.html', '%d.html'],
         'bodyPattern':{"tag":"div", "class":["articleBody"]},
         'myposPattern': {"tag":"div", "class":["position"]},
         #'myposXpath':'//div[@class="tz_more"]/div/p[1]/text()',
         'textXpath':'//div[@class="articleTitle"]/h1/text()',
         'imgPattern':ur'(?is)(<img.*?>)',
         'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
         'isAlbum':1
        },

     '3lian.com':{
         'category':'动漫',
         'domain':'3lian.com',
         'sourceUrl':{
                 'http://3lian.com/gif/more/08/index.html':234,
                 'http://3lian.com/gif/more/04/index.html':54,
                 'http://3lian.com/gif/more/51/index.html':26,
             },
         'urlPattern':'http://3lian.com/gif/\d+/\d+-\d+/.*?.html',
         'fenyePattern':['.html', '_%d.html'],
         'bodyPattern':{"tag":"div", "class":["art_cont1"]},
         'myposPattern': {"tag":"div", "class":["logo_L"]},
         'textPattern':{"tag":"div", "class":["tips"]},
         'imgPattern':ur'(?is)(<img.*?>)',
         'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
         'detailFenyePattern':['.html', '_%d.html'],
         'isAlbum':1
        },

    'tu.kumi.cn':{
        'category':'动漫',
        'domain':'tu.kumi.cn',
        'sourceUrl':{
                'http://tu.kumi.cn/l/122-0-0-1.html':5,
                'http://tu.kumi.cn/l/123-0-0-1.html':6,
                'http://tu.kumi.cn/l/124-0-0-1.html':3,
                'http://tu.kumi.cn/cosplay':1,
                'http://tu.kumi.cn/meishaonv':1,
                'http://tu.kumi.cn/tongren':1,
                'http://tu.kumi.cn/zhoubian':1,
            },
        'urlPattern':'http://tu.kumi.cn/n/\d+-\d+-0-0-1.html',
        'fenyePattern':['1.html', '%d.html'],
        'bodyPattern':{"tag":"ul", "class":["tu"]},
        'myposPattern': {"tag":"div", "class":["weizhi"]},
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|JPG|png)',
        #'imgReplace':[['img.zhuoku.com','bizhi.zhuoku.com']],
        'textXpath':'//p[@class="katoon"]/text()',
        'imgReplace':[['sl.jpg','610x455.jpg']],
	    'detailFenyePattern':['1.html', '%d.html'],
        'isAlbum':1
    },

   'win4000.com':{
        'category':'动漫',
        'domain':'win4000.com',
        'sourceUrl':{
                'http://www.win4000.com/meinvtag41_1.html':11,
                'http://www.win4000.com/wallpaper_192_0_0_1.html':276,
                'http://www.win4000.com/mobile_2346_0_0_1.html':23,
                'http://www.win4000.com/mobile_2349_0_0_1.html':24,
                'http://www.win4000.com/meinvtag26_1.html':4,
            },
        'urlPattern':'http://www.win4000.com/(meinv\d+|wallpaper_detail_\d+).html',
        'fenyePattern':['1.html', '%d.html'],
        'bodyPattern':{"tag":"ul", "class":["scroll-img", "ulBigPic"]},
        'myposPattern': {"tag":"p", "class":["mei-location"]},
        #'myposXpath':'//div[@class="pageWrapper"]/div/a/text()',
        'textPattern':{"tag":"div", "class":["where", "ptitle"]},
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
        'imgReplace':[['_100.jpg','']],
        #'detailFenyePattern':['.html', '_%d.html'],
        'isAlbum':1
    },

    'zol.com.cn':{
        'category':'动漫',
        'domain':'zol.com.cn',
        'sourceUrl':{
                'http://desk.zol.com.cn/dongman/1.html':34,
                'http://desk.zol.com.cn/dongman/p3/1.html':3,
                'http://sj.zol.com.cn/bizhi/dongman/1.html':30,
            },
        'fenyePattern':['1.html', '%d.html'],
        'urlPattern':'http://sj.zol.com.cn/bizhi/((detail_\d+_\d+)|(\d+_\d+_\d+)).html',
        'bodyPattern':{"tag":"ul", "id":["showImg"]},
        'myposPattern': {"tag":"div", "class":["location"]},
        #'myposXpath':'//div[@class="pageWrapper mainWrapper"]/div/a/text()',
        'textXpath':'//div[@class="wrapper photo-tit clearfix"]/h3/a/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*\.(jpg|jpeg|gif|JPG|png)',
        'imgReplace':[['s144x90','s960x600'], ['s120x90', 's320x510']],
        #'detailFenyePattern':['.html', '_%d.html'],
        'fenyePattern':['1.html', '%d.html'],
        'isAlbum':1
    },
    'sootuu.com':{
        'category':'动漫',
        'domain':'sootuu.com',
        'sourceUrl':{
                'http://www.sootuu.com/browse/1823/15_1823_1.htm':9,
                'http://www.sootuu.com/browse/1755/15_1755_1.htm':100,
                'http://www.sootuu.com/browse/1809/15_1809_1.htm':17,
                'http://www.sootuu.com/browse/2736/15_2736_1.htm':95,
                'http://www.sootuu.com/browse/1868/15_1868_1.htm':40,
                'http://www.sootuu.com/browse/1909/15_1909_1.htm':2,
                'http://www.sootuu.com/browse/1907/15_1907_1.htm':14,
                'http://www.sootuu.com/browse/1906/15_1906_1.htm':12,
                'http://www.sootuu.com/browse/1905/15_1905_1.htm':3,
                'http://www.sootuu.com/browse/1904/15_1904_1.htm':24,
                'http://www.sootuu.com/browse/1903/15_1903_1.htm':20,
                'http://www.sootuu.com/browse/1921/15_1921_1.htm':52,
                'http://www.sootuu.com/browse/1808/15_1808_1.htm':100,
            },
        'fenyePattern':['1.htm', '%d.htm'],
        'urlPattern':'http://www.sootuu.com/material/((\d+/\d+)|(\d+-\d+/\d+-\d+-\d+)).htm',
        'myposPattern': {"tag":"p", "class":["tips_left"]},
        'bodyPattern':{"tag":"div", "class":["content_pic"]},
        #'textPattern':{"tag":"div", "class":["al_tit"]},
        'textXpath':'//div[@class="content_l_ul"]/h1/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|gif|JPG|png)',
        'isAlbum':1
    },
    'bz55.com':{
        'category':'动漫',
        'domain':'bz55.com',
        'sourceUrl':{
                'http://www.bz55.com/dongmanbizhi/list_3_1.html':7,
            },
        'fenyePattern':['1.html', '%d.html'],
        'urlPattern':'http://www.bz55.com/xiaoshuo/\d+.html',
        'myposPattern': {"tag":"div", "class":["goback"]},
        'bodyPattern':{"tag":"ul", "class":["gameMain-ul"]},
        'textPattern':{"tag":"div", "class":["intro-wrap"]},
        #'textXpath':'//div[@class="text_wrap"]/h2/a/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|gif|JPG|png)',
        #'imgReplace':[['/t/','/pre/']],
        #'detailFenyePattern':['', 'index_%d.html'],
        'isAlbum':1
    },
    'dongman.tuku.com':{
        'category':'动漫',
        'domain':'dongman.tuku.com',
        'sourceUrl':{
                'http://dongman.tuku.com/index.html':41,
            },
        'fenyePattern':['.html', '_%d.html'],
        'urlPattern':'http://dongman.tuku.com/\d+/\d+.html',
        #'myposPattern': {"tag":"p", "class":["tips_left"]},
        'bodyPattern':{"tag":"img", "id":["bigPic"]},
        'textXpath':'//div[@class="title"]/h1/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|gif|JPG|png)',
        #'imgReplace':[['_100.jpg','']],
        'detailFenyePattern':['1.html', '%d.html'],
        'isAlbum':1
    },
    'qqmofasi.com':{
        'category':'动漫',
        'domain':'qqmofasi.com',
        'sourceUrl':{
                'http://www.qqmofasi.com/qqtupian/katongdongman4/page-1.html':160,
            },
        'fenyePattern':['1.html', '%d.html'],
        'urlPattern':'http://www.qqmofasi.com/qqtupian/\d+.html',
        'myposPattern': {"tag":"div", "class":["poslink"]},
        'bodyPattern':{"tag":"ul", "id":["detail_header_list"]},
        'textXpath':'//div[@class="article_r"]/h1/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|gif|JPG|png)',
        #'imgReplace':[['_100.jpg','']],
        'detailFenyePattern':['1.html', '%d.html'],
        'isAlbum':1
    },
    '16pic.com':{
        'category':'动漫',
        'domain':'16pic.com',
        'sourceUrl':{
                'http://www.16pic.com/photo/115_new_1.html':338,
            },
        'fenyePattern':['1.html', '%d.html'],
        'urlPattern':'http://www.16pic.com/photo/pic_\d+.html',
        'myposPattern': {"tag":"div", "class":["position"]},
        'bodyPattern':{"tag":"ul", "class":["img_show"]},
        'textXpath':'//div[@class="works_img"]/h1/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|gif|JPG|png)',
        #'imgReplace':[['_100.jpg','']],
        'detailFenyePattern':['1.html', '%d.html'],
        'isAlbum':1
    },
    'wallcoo.com':{
        'category':'动漫',
        'domain':'wallcoo.com',
        'sourceUrl':{
                'http://www.wallcoo.com/cartoon/index1.htm':23,
            },
        'fenyePattern':['1.htm', '%d.htm'],
        'urlPattern':'http://www.wallcoo.com/cartoon/.*?/index.html',
        'myposPattern': {"tag":"div", "id":["place"]},
        'bodyPattern':{"tag":"div", "id":["thums"]},
        'textXpath':'//div[@id="pic_intro"]/table/tbody/tr/td/ul/li/a[2]/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|gif|JPG|png)',
        'imgReplace':[['/s/','/images/'], ['s.jpg','.jpg']],
        'detailFenyePattern':['.html', '%d.html'],
        'isAlbum':1
    },
    'haobizhi.com':{
        'category':'动漫',
        'domain':'haobizhi.com',
        'sourceUrl':{
                'http://www.haobizhi.com/dongman/1.htm':237,
            },
        'fenyePattern':['1.htm', '%d.htm'],
        'urlPattern':'http://www.haobizhi.com/bizhi/\d+.htm',
        'myposPattern': {"tag":"div", "class":["breadcrumb"]},
        'bodyPattern':{"tag":"div", "class":["pic"]},
        'textXpath':'//div[@class="tit"]/h1/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|JPG|png)',
        #'imgReplace':[['/s/','/images/'], ['s.jpg','.jpg']],
        #'detailFenyePattern':['.html', '%d.html'],
        'isAlbum':1
    },
    'bbs.gfan.com':{
        'category':'动漫',
        'domain':'bbs.gfan.com',
        'sourceUrl':{
                'http://bbs.gfan.com/forum.php?mod=forumdisplay&fid=11&typeid=28&filter=typeid&typeid=28&page=1':37,
            },
        'fenyePattern':['page=1', 'page=%d'],
        'urlPattern':'http://bbs.gfan.com/forum.php/?mod=viewthread&tid=\d+&extra=page.*?3D28',
        'myposPattern': {"tag":"div", "class":["z"]},
        'bodyPattern':{"tag":"div", "class":["f_fsz"]},
        'textXpath':'//h1[@class="ts"]/a/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|JPG|png)',
        #'imgReplace':[['/s/','/images/'], ['s.jpg','.jpg']],
        #'detailFenyePattern':['.html', '%d.html'],
        'isAlbum':1
    },
    'enterdesk.com':{
        'category':'动漫',
        'domain':'enterdesk.com',
        'sourceUrl':{
                'http://www.enterdesk.com/zhuomianbizhi/dongmankatong/index.html':55,
            },
        'fenyePattern':['index.html', '%d.html'],
        'urlPattern':'http://www.enterdesk.com/bizhi/\d+.html',
        'myposPattern': {"tag":"div", "class":["thislocation"]},
        'bodyPattern':{"tag":"div", "class":["arcpic"]},
        'textXpath':'//div[@class="sbody"]/h1/text()',
        'imgPattern':ur'(?is)(<img.*?>)',
        'imgUrlPattern':'http.*?\.(jpg|jpeg|JPG|png)',
        #'imgReplace':[['/s/','/images/'], ['s.jpg','.jpg']],
        #'detailFenyePattern':['.html', '%d.html'],
        'isAlbum':1
    },
}
